# change build process to circleci
version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Update
          command: apt update && apt upgrade -y
      - run:
          name: Install package
          command: apt install -y pandoc
      - run:
          name: convert md to html
          command: build.sh

