# change build process to circleci
version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Update
          command: apt update && apt upgrade -y
      - run:
          name: Install package
          command: apt install -y pandoc
      - deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bash deploy.sh
            fi

